Refactor
schulen-im-chaos/website pull request #3
Opened 2023-08-10 13:27 UTC by nwrenger

The current version of my refactoring can be seen in here, ask here any questions and post here improvements. If we are finished with refactoring the [current site](https://schulenimchaos.de/), this pull request will be merged.

2023-08-11 08:46 UTC, alexcoder04 commented
Is Prettier set up on you system (I assume you use VSCode)? So that the formatting is consistent across the whole project?

2023-08-11 10:13 UTC, alexcoder04 reviewed
Very nice, thank you!!! 🙏

I would say, the plan for now is:
 - add other pages (there is not much to refactor, just check that the layout is ok)
 - finish backend
 - switch frontend to API v2 (with support for search and tags)
 - merge this PR

sorry for bombarding you with a bunch of critical comments, I just wrote down everything that is mir aufgefallen.

2023-08-11 10:13 UTC, alexcoder04 commented on README.md
> + - [ ] add github workflow for automatically deploying and running this website as a github page
we would have to think once again about this, and clarify stuff like domain, ssl certs etc

2023-08-11 10:13 UTC, alexcoder04 commented on src/app.css
> +@tailwind utilities;
why

2023-08-11 10:13 UTC, alexcoder04 commented on src/app.html
> +</html>
is Prettier set up correctly?

2023-08-11 10:13 UTC, alexcoder04 commented on src/components/basic/Button.svelte
maybe we could make ButtonGradient to somehow derive from this to avoid duplicated code?

2023-08-11 10:13 UTC, alexcoder04 commented on src/components/basic/Spinner.svelte
thank you for fixing this, I've nearly gone mad about this bug

2023-08-11 10:13 UTC, alexcoder04 commented on src/components/materials/Overview.svelte
> +				<ParagraphDefault>No items found.</ParagraphDefault>
tbh I'm not quite sure whether it looks ok with the paragraphs, because the flex layout squeezes them into narrow columns, but otherwise we'd have to modify the whole layout if there is an error

2023-08-11 10:13 UTC, alexcoder04 commented on src/components/materials/browse/View.svelte
> +	function getParam(key) {
I guess this could go into the lib folder because we will definitively use it in more components but I'm not sure whether it'll work with $page

2023-08-11 10:13 UTC, alexcoder04 commented on src/components/materials/browse/View.svelte
> +{#await itemsPromise}
:+1:

2023-08-11 10:13 UTC, alexcoder04 commented on src/components/materials/browse/View.svelte
> +		itemsPromise = await getJson(
This will be a post request in API v2, because the url is way too long and complicated

2023-08-11 10:13 UTC, alexcoder04 commented on src/components/materials/browse/View.svelte
> +		<ParagraphDefault>Unexpected data structure received.</ParagraphDefault>
Once again, rather German messages in UI

2023-08-11 10:13 UTC, alexcoder04 commented on src/components/navigation/NavItem.svelte
> +		class="cursor-pointer text-gray-900 dark:text-gray-300 hover:text-black dark:hover:text-white {$page
Thank you for figuring this out!
Do you think, the contrast is enough to see the difference between active and inactive items?

2023-08-11 10:13 UTC, alexcoder04 commented on src/routes/materials/browse/+page.svelte
> +<!-- Todo: Add Search -->
I would say we'll add all of this during this PR, when I'll be ready with the backend (will probably be today, but can't promise)

2023-08-11 10:13 UTC, alexcoder04 commented on src/routes/materials/contribute/+page.svelte
> +<ul class="list-disc ml-6 pb-4">
Do we need an own List component? It's used a couple of times across the page

2023-08-11 10:13 UTC, alexcoder04 commented on tailwind.config.js
> +		},
why do we need to whitelist this? (I'm too dumb to understand)

2023-08-11 10:13 UTC, alexcoder04 commented on tailwind.config.js
> +	plugins: [],
are we going to use trailing commas everywhere? If so, we should configure Prettier respectively

2023-08-11 10:27 UTC, nwrenger commented on tailwind.config.js
> +		},
yeah, try it, without that it won’t work

2023-08-11 23:36 UTC, nwrenger commented on tailwind.config.js
> +	plugins: [],
forgot prettier

2023-08-11 23:41 UTC, nwrenger commented on src/routes/materials/contribute/+page.svelte
> +<ul class="list-disc ml-6 pb-4">
nur 2 mal, das passt so

2023-08-11 23:42 UTC, nwrenger commented on src/routes/materials/browse/+page.svelte
> +<!-- Todo: Add Search -->
*Probably today...*

2023-08-11 23:42 UTC, nwrenger commented on src/components/navigation/NavItem.svelte
> +		class="cursor-pointer text-gray-900 dark:text-gray-300 hover:text-black dark:hover:text-white {$page
fixed that

2023-08-11 23:44 UTC, nwrenger commented on src/components/materials/browse/View.svelte
> +		<ParagraphDefault>Unexpected data structure received.</ParagraphDefault>
yes did that

2023-08-11 23:49 UTC, nwrenger commented on src/components/materials/browse/View.svelte
> +		itemsPromise = await getJson(
I'm not sure what the issue is with the current approach. It seems that even the limitation/problems involves a POST request, as all the data is being read from a URL (in the frontend) which then is sent in the request (to the api).

2023-08-11 23:49 UTC, nwrenger commented on src/components/materials/browse/View.svelte
> +{#await itemsPromise}
:+1:

2023-08-11 23:55 UTC, nwrenger commented on src/components/materials/browse/View.svelte
> +	function getParam(key) {
nope doesnt work...

2023-08-11 23:55 UTC, nwrenger commented on src/components/materials/Overview.svelte
> +				<ParagraphDefault>No items found.</ParagraphDefault>
is fine for error messages

2023-08-11 23:56 UTC, nwrenger commented on src/components/basic/Button.svelte
i like having two different components...

2023-08-11 23:56 UTC, nwrenger commented on src/app.html
> +</html>
now it is

2023-08-11 23:56 UTC, nwrenger commented on src/app.css
> +@tailwind utilities;
idk

2023-08-11 23:57 UTC, nwrenger commented on README.md
> + - [ ] add github workflow for automatically deploying and running this website as a github page
Yeah, we did talk about that a bit, any further questions?

2023-08-11 23:57 UTC, nwrenger commented
finished all todos, waiting for your review...

2023-08-12 18:26 UTC, alexcoder04 requested changes
love it, looks great! 🙏
some points of criticism are still there, see my comments.
if they're fixed as well, I can deploy it to gh pages (would have to setup the domain name)

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/basic/Button.svelte
> +	<a href={!external ? `${base}${href}` : href} class={style} {target}>
why do we need "base"?

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/navigation/NavDropdown.svelte
should disappear if clicked on one of the links in it

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/basic/Dropdown.svelte
> +										class="mr-2 rounded bg-inherit"
the checkboxes are still not properly styled for me, you still haven't figured out why?

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/basic/Dropdown.svelte
> +					<div class="overflow-hidden rounded-b-lg">
would make these buttons 100% width (w-full)

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/basic/Dropdown.svelte
this component looks huge, but we cannot split it into multiple, can we? (maybe make the list itself separate?)

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/basic/ErrorPage.svelte
> +	<ParagraphDefault
tbh, I've got no idea why prettier produces weird formatting like this...
If you format it nicely manually and then re-format, it looks ok

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/materials/browse/Filter.svelte
> +		Wrong Data Structure
deutsch

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/navigation/Footer.svelte
> -				<FooterGroupItem href={DISCORD_LINK} target="_blank">
"external" parameter should imply "target=_blank", so it doesn't have to be specified explicitely

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/navigation/FooterGroupItem.svelte
> +	<a href={!external ? `${base}${href}` : href} {target} class="hover:underline">
external implies target=_blank

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/navigation/NavBar.svelte
> +				href="https://discord.com/invite/nWd8yZ4HWY"
use global variable for that link (it may change)

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/navigation/NavDropdown.svelte
looks nice, but add some more padding

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/navigation/NavBar.svelte
more padding bottom in the nav list on mobile to separate it from the green discord button more clearly

2023-08-12 18:26 UTC, alexcoder04 commented on src/components/navigation/NavItem.svelte
did you change the colors? the diference between active and non-active seems much more noticeable to me now

2023-08-12 18:26 UTC, alexcoder04 commented on src/routes/contact/+page.svelte
prevent accidental spam on bad internet (we already had problems with that):
submit clicked -> button inactive (not clickable) -> form cleared -> alert whether everything ok

2023-08-12 18:26 UTC, alexcoder04 commented on src/routes/contact/+page.svelte
could you center the contact form? it is on the left side on large screens.
otherwise looks great, could not tell difference to flowbite

2023-08-12 18:26 UTC, alexcoder04 commented on src/routes/legal/+page.server.js
to you as a svelte pro: can/should this be done with goto?

2023-08-12 18:26 UTC, alexcoder04 commented on src/routes/legal/data-protection/+page.svelte
> +<h3 class="text-base md:text-lg px-2 md:px-0">Speicherdauer</h3>
maybe Subheading component for h3?

2023-08-12 18:26 UTC, alexcoder04 commented on tailwind.config.js
>  			medium: "20px",
medium should be same as base (in best case scenario it should not exist at all, but i am afraid that i used both in the code).

maybe adjust other font sizes as well?

2023-08-12 18:26 UTC, alexcoder04 commented on .github/workflows/deploy.yml
:star_struck:

2023-08-12 18:31 UTC, nwrenger commented on src/components/basic/Button.svelte
> +	<a href={!external ? `${base}${href}` : href} class={style} {target}>
Because of GitHub pages

2023-08-12 18:32 UTC, nwrenger commented on src/components/basic/Dropdown.svelte
> +										class="mr-2 rounded bg-inherit"
Idk why, maybe tailwinds purge

2023-08-12 18:57 UTC, nwrenger commented on src/components/navigation/NavItem.svelte
Yes, I did change the colors…

2023-08-12 19:00 UTC, nwrenger commented on src/routes/legal/+page.server.js
Yes, I’ve changed view.svelte to be reactive for that

2023-08-12 19:28 UTC, nwrenger commented on src/components/navigation/NavDropdown.svelte
Made this for mobile, thought it looks cooler on desktop…

2023-08-12 19:32 UTC, nwrenger commented on src/components/basic/Dropdown.svelte
It’s a very unique component, that can do check box drop-downs and normal dropdowns, also it’s not tooo long (130) I think it’s ok

2023-08-12 21:36 UTC, nwrenger commented on src/components/navigation/NavDropdown.svelte
done

2023-08-12 21:47 UTC, nwrenger commented on src/components/basic/Dropdown.svelte
> +					<div class="overflow-hidden rounded-b-lg">
done

2023-08-12 21:50 UTC, nwrenger commented on src/components/basic/ErrorPage.svelte
> +	<ParagraphDefault
nah, even normally manually doesn't fix that, maybe a config issue?

2023-08-12 21:51 UTC, nwrenger commented on src/components/materials/browse/Filter.svelte
> +		Wrong Data Structure
done

2023-08-12 21:53 UTC, alexcoder04 commented on src/components/basic/ErrorPage.svelte
> +	<ParagraphDefault
We should definitely dive deeper into how formatting works

2023-08-12 21:54 UTC, nwrenger commented on src/components/navigation/Footer.svelte
> -				<FooterGroupItem href={DISCORD_LINK} target="_blank">
done

2023-08-12 21:56 UTC, nwrenger commented on src/components/navigation/NavBar.svelte
> +				href="https://discord.com/invite/nWd8yZ4HWY"
done

2023-08-12 21:58 UTC, nwrenger commented on src/components/navigation/NavBar.svelte
done

2023-08-12 22:07 UTC, nwrenger commented on src/components/navigation/FooterGroupItem.svelte
> +	<a href={!external ? `${base}${href}` : href} {target} class="hover:underline">
done

2023-08-12 22:09 UTC, nwrenger commented on src/components/navigation/NavDropdown.svelte
done

2023-08-12 22:13 UTC, nwrenger commented on src/routes/contact/+page.svelte
done

2023-08-12 22:14 UTC, nwrenger commented on src/routes/contact/+page.svelte
done

2023-08-12 22:15 UTC, nwrenger commented on src/routes/legal/+page.server.js
no, redirect is "from svelte", no js funtion, so we dont need to change that

2023-08-12 22:18 UTC, nwrenger commented on src/routes/legal/data-protection/+page.svelte
> +<h3 class="text-base md:text-lg px-2 md:px-0">Speicherdauer</h3>
done

2023-08-12 22:19 UTC, nwrenger commented on tailwind.config.js
>  			medium: "20px",
medium = base;

2023-08-12 22:19 UTC, nwrenger commented on .github/workflows/deploy.yml
gonna push this, lets see how it works...

2023-08-12 22:28 UTC, nwrenger commented on src/components/basic/Button.svelte
> +	<a href={!external ? `${base}${href}` : href} class={style} {target}>
removed that...

2023-08-12 22:36 UTC, nwrenger commented
Finished the requested changes (GitHub wants me to use their change system, but I wanted to make those changes on my editor)

2023-08-12 22:38 UTC, merged

2023-08-13 13:00 UTC, nwrenger commented on src/components/basic/Dropdown.svelte
> +										class="mr-2 rounded bg-inherit"
added to [To Do's](https://github.com/schulen-im-chaos/schulen-im-chaos.github.io#to-dos)

2023-08-13 13:00 UTC, nwrenger commented on src/components/basic/ErrorPage.svelte
> +	<ParagraphDefault
added to [To Do's](https://github.com/schulen-im-chaos/schulen-im-chaos.github.io#to-dos)